version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
